version: "3.9"

services:
  # proxy:
  #   container_name: proxy
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: "unless-stopped"
  #   networks:
  #     - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    depends_on:
      - redis
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - backend
    volumes:
      - data:/data/db
      - data:/data/configdb

  redis:
    container_name: redis
    image: redis
    restart: "unless-stopped"
    networks:
      - backend
    volumes:
      - cache:/data

networks:
  backend:
    driver: bridge

volumes:
  cache:
    driver: local
  data:
    driver: local
  node_modules:
    driver: local
