services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://romain:romain@postgres:5432/express-auth
      - REDIS_URL=redis://redis
      - NODE_ENV=production
    restart: "unless-stopped"
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: romain
      POSTGRES_PASSWORD: romain
      POSTGRES_DB: express-auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: "unless-stopped"
    volumes:
      - cache:/data

volumes:
  cache:
  postgres_data:
  node_modules:
